"""
Article dataclass — the core data model for the WSJ digest pipeline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Article:
    # --- Core identity ---
    title: str
    url: str

    # --- Source metadata ---
    source_section: str          # e.g. "world", "markets", "tech"
    source_feed: str             # e.g. "WSJ World News" or "wsj.com/section"
    publish_time: datetime       # UTC; parsed from RSS pubDate or page meta

    # --- Classification (set by scorer) ---
    category: Optional[str] = None        # "Global" | "Market" | "Stock" | "Tech"
    category_score: float = 0.0           # keyword-match confidence 0–100

    # --- Scoring components (set by scorer) ---
    importance_score: float = 0.0
    recency_score: float = 0.0
    market_relevance_score: float = 0.0
    total_score: float = 0.0              # weighted composite 0–100

    # --- Raw content (from RSS description / scraped lead) ---
    lead_text: str = ""
    author: str = ""
    full_text: str = ""            # body paragraphs from full article page; never rendered to output
    full_text_fetched: bool = False  # True once a fetch was attempted (success or fail)

    # --- Generated by summarizer ---
    summary: str = ""
    why_it_matters: list = field(default_factory=list)  # list[str], 1–2 bullets

    # --- Pipeline state flags ---
    fetch_error: bool = False
    fetch_error_msg: str = ""
    is_duplicate: bool = False
    duplicate_of_url: str = ""

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def age_hours(self) -> float:
        """Return the article's age in hours relative to now (UTC)."""
        now = datetime.now(timezone.utc)
        pub = self.publish_time
        # Make publish_time tz-aware if it is naive (assume UTC)
        if pub.tzinfo is None:
            pub = pub.replace(tzinfo=timezone.utc)
        delta = now - pub
        return delta.total_seconds() / 3600

    def to_dict(self) -> dict:
        """Serialise to a plain dict suitable for JSON or template rendering."""
        pub = self.publish_time
        if pub.tzinfo is None:
            pub = pub.replace(tzinfo=timezone.utc)
        return {
            "title": self.title,
            "url": self.url,
            "source_section": self.source_section,
            "source_feed": self.source_feed,
            "publish_time": pub.isoformat(),
            "publish_time_human": pub.strftime("%b %d, %Y %H:%M UTC"),
            "category": self.category,
            "total_score": round(self.total_score, 1),
            "importance_score": round(self.importance_score, 1),
            "recency_score": round(self.recency_score, 1),
            "market_relevance_score": round(self.market_relevance_score, 1),
            "lead_text": self.lead_text,
            "author": self.author,
            "summary": self.summary,
            "why_it_matters": self.why_it_matters,
        }
